### ISSUE TITLE
Collections "set" not matched ?

### ISSUE THREAD

**Issue by Mrpink200** [gboudreau/XBMCnfoMoviesImporter.bundle#108]
Hi

I successfully setup the plugin in plex, and test nfo info is well imported but i get an issue with collections. Collections are active in my plex collection 
Collections are set with the follwing flags using tinymediamanager but plex seems to ignore it in the nfo files while refreshing the info. Any idea ? Is it a bug or have i missed something ?

Ex :
<set>
    <name>Edition Criterion</name>
    <overview/>
  </set>

**Comment by SlrG** [comment]
`<set></set>` and
 `    <set>
        <name></name>
        <overview></overview>
    </set>
`
should work fine. Additionally you can enable using tags for collection creation in the agents settings. As it does not work for you, please enable debug logging in the agents settings and check your log files to see what is going wrong.

**Comment by Mrpink200** [comment]
many thanks for your quick reply SIrG.
I tried to enable / disable  collection in my library. Enable / disable "Enable generating Collections from tags" in the agent setting (and letting everything else by default) ... but the collection is not added while refreshing a test movie (while a change on film tags are working)
i do not get it :(

**Comment by Mrpink200** [comment]
got it; it was because my film had a lock on the collection details that avoided the nfo tag to replace it :)

**Comment by SlrG** [comment]
I'm glad you could solve the problem. :)
