### ISSUE TITLE
can't import moviename-poster.png

### ISSUE THREAD

**Issue by PHCSJC** [gboudreau/XBMCnfoMoviesImporter.bundle#111]
for example, I have a movie in same one floder
ipx-443-C-.mp4
ipx-443-C-poster.png
ipx-443-C-fanart.png
then I use XBMCnfoMoviesImporter scan, and I found fanart can show, but poster can't show.
help! thanks!
Plex Version 1.18.6.2368

**Comment by SlrG** [comment]
Only .jpg is supported not .png.

**Comment by PHCSJC** [comment]
@SlrG 
do you have any plan add support .png? because I have many png pic.
thanks!

**Comment by SlrG** [comment]
I stopped using plex and developing the agents. I'm still answering questions, but that's all I can do at the moment. Sadly no one has picked up the project.

As a quick fix, I would recommend batch conversion tools (e.g. the batch function of IrfanView) which will convert all your pngs to jpgs keeping the original files and the directory structure. It will increase the needed storage space, but not by much, on today's standards. If png support is added by someone later, its easy enough to remove the jpgs, then.

**Comment by PHCSJC** [comment]
ok, thanks!
