### ISSUE TITLE
Export function

### ISSUE THREAD

**Issue by BH1NBN** [gboudreau/XBMCnfoMoviesImporter.bundle#112]
Have you thought about exporting the current media files through this plug-in to nfo and actor posters and other information? In case the media library is damaged and rebuilt faster!

**Comment by SlrG** [comment]
AFAIK this is not possible. Plex provides agents only with the ability to add artwork to the database not extract it. If anybody has different and more knowledge than me and wants to implement this, pull requests are always welcome.
