### ISSUE TITLE
Multiple Collections Tag (Also applies to XBMCnfoTV)

### ISSUE THREAD

**Issue by purevertigo** [gboudreau/XBMCnfoMoviesImporter.bundle#113]
Adding more than one plex collection tag, eg. <set>Batman / DC</set> 
or 
<set>Batman</set>
<set>DC</set>

results in the forward-slash getting scraped or only the first instance being picked up in the second case.

**Comment by SlrG** [comment]
Thanks for reporting. I stopped working on the agents however. If anybody wants to pick them up, please contact Guillaume. Pull requests are also welcome.

**Comment by purevertigo** [comment]
@SlrG sad to see you go. I remember working with you on these years ago via the forum.

**Comment by skinnerback** [comment]
I've been using tag to add files to a collection and it supports multiple by repeating.
```
<tag>Batman</tag>
<tag>DC</tag>
```

**Comment by purevertigo** [comment]
> I've been using tag to add files to a collection and it supports multiple by repeating.
> 
> ```
> <tag>Batman</tag>
> <tag>DC</tag>
> ```

Wow! Thanks for that. Works beautifully. Fantastic workaround.

**Comment by purevertigo** [comment]
I'm closing this issue as XBMC/Kodi by design only supports one movie set (collection) per movie with the set feature so the better way is the tag feature.
