### ISSUE TITLE
Local asset management with plex - actor thumbs

### ISSUE THREAD

**Issue by pimalel233** [gboudreau/XBMCnfoMoviesImporter.bundle#128]
Hello there,
firstly let me say it is a great plugin that maxes Plex works as it should always work in my case.

I use Plex on Windows 10 with your XBMC plugins and WebTools and tinyMediaManager to manage my assets.

For the most part everything works as I want which means that poster and fanart with nfo are located with the movie that gets imported. Everything is loaded accordingly.
But the actor thumbs are still added to the database as links to the Internet. TinyMediaManager can download actor thumbs to .actors that I tried to place in one place which I would like to use as my main actor thumb folder and link it within the plugin which if I understand correctly, is actor thumb location set to global with path to movie library or global actor folder set to the place with images ex - \\localhost\.actors where .actors is share on my pc.

But - which I think is the issue - tinyMediaManager still writes internet path in its nfo, for example:
http://prntscr.com/svgnt6

I would like it to get ignored in favor of local asset like with posters/fanarts which is named properly in the global path .actors\name_surname.jpg. Is it possible to do, or am I making a mistake here which I am not seeing?

**Comment by ReenigneArcher** [comment]
Local assets don't support actors.
