### ISSUE TITLE
Content Rating 

### ISSUE THREAD

**Issue by kuzco1** [gboudreau/XBMCnfoMoviesImporter.bundle#62]
Hello,
I am using this plugin (latest version - V 1.1-24) with my Plex on Windows (also latest version - 0.9.12.11) to import all my movies.
The xbmc movie.nfo is created by tmm (Tiny Media Manager 2.6.9).

Everything is imported well, only the content rating is wrong. The movie.nfo has the following entry:
mpaa has: <mpaa>DE:FSK 16 / DE:FSK16 / DE:16 / DE:ab 16</mpaa>
certification has: <certification>DE:FSK 16 / DE:FSK16 / DE:16 / DE:ab 16</certification>
but in Plex I do only see "DE" for Rating.

When editing movie.nfo manually:
before:
certification has: DE:FSK 16 / DE:FSK16 / DE:16 / DE:ab 16
after:
certification has: Germany:FSK 16 / Germany:FSK16 / Germany:16 / Germany:ab 16
I see "de/FSK 16" for rating in Plex.

Any help is appreciated.

Regards
kuzco1

**Comment by SlrG** [comment]
Do you still have this problem? I can try to fix it if you like.

**Comment by kuzco1** [comment]
Hi, thanks for asking.
I have played a little bit and found a quick and dirty solution:

Have edited contents/codes/__init.py__

NEW:
COUNTRY_CODES = {
  'Australia': 'Australia,AU',
  'Canada': 'Canada,CA',
  'France': 'France,FR',
  'Germany': 'Germany,DE',
  'Netherlands': 'Netherlands,NL',
  'United Kingdom': 'UK,GB',
  'United States': 'USA,',
}

NEW:
COUNTRY_CODES = {
  'Australia': 'Australia,AU',
  'Canada': 'Canada,CA',
  'DE': 'DE,DE',  
  'France': 'France,FR',
  'Germany': 'Germany,DE',
  'Netherlands': 'Netherlands,NL',
  'United Kingdom': 'UK,GB',
  'United States': 'USA,',
}

Unfortunately I do not seek the "content rating" info on the every movie screen info, only when clicking on info.

**Comment by SlrG** [comment]
Please give this [testing version](https://github.com/SlrG/XBMCnfoMoviesImporter.bundle/archive/master.zip) a go. It should hopefully fix your problem.

**Comment by kuzco1** [comment]
Hello, sorry for the late replay.
have tested Ver. 1.1-38-g2d77b79-144 and it works perfectly.

Many many thanks for this update. You made my day ! :-)

Thanks again.

Regards

**Comment by SlrG** [comment]
Cool. :) Thanks for reporting back. I'll close the issue as solved.
