### ISSUE TITLE
Sort Title: Import from metadata if available, fallback to title if not?

### ISSUE THREAD

**Issue by rfgamaral** [gboudreau/XBMCnfoMoviesImporter.bundle#64]
I don't like how Plex handles sorting titles, it strips "the" (and similar) from the titles and uses the rest for sorting. For instance, "The Butler" will have "Butler" as `Sort Title` and sort that movie under `B`. And there's not even an option to turn this behavior off.

As such, it would be nice to have this option on this importer agent. I tried to do it myself, but I failed. Maybe I did something wrong, I don't know.

Some of my .nfos have the `<sorttitle>` tag, some don't (most don't actually). My idea is to get that tag if available and use it, if it's not, use the `<title>` tag instead of letting Plex handle it (this could be an additional importer setting, to get the sort title from the title if it's not available or let Plex handle it).

I'm no Python expert but I tried to mimic the code used for the original title in the `update` method, using `metada.title_sort` (AFAIK, that's the field Plex uses). But it didn't work. Yes, I restarted Plex and then refreshed the movies. It didn't work.

Thoughts?

**Comment by SlrG** [comment]
Thats sadly a known problem. :( Plex does not use that attribute in the frontend. So even if you fill it, it will have no effect. I already tried it myself. This behaviour will need to be changed by the plex devs. So nothing we can do about it at the moment.

**Comment by rfgamaral** [comment]
Are you sure it doesn't? If I remember correctly, I believe I tried to edit the metadata of one my movies, changed the Sort Title to include "the" and locked that field. The movie was then sorted properly...

**Comment by SlrG** [comment]
Well, if you change the sort title field in the webfront yourself, then yes sorting by that will work. What doesn't work is changing title_sort and having that distribute to the sort title field in the webfront. You can have a look at plex' [local media assets agent](https://github.com/plexinc-agents/LocalMedia.bundle/blob/master/Contents/Code/videohelpers.py). There it is done like this:
`
try:
  title_sort = tags["sonm"][0]
  item.title_sort = title_sort
except: pass
`
But even that doesn't work. (At least not the last time I tried.)

**Comment by rfgamaral** [comment]
I see... That sucks :(

Feel free to close this issue and thank you for your time.

**Comment by SlrG** [comment]
It seems the plex devs have done the necessary background work, for this to finally start working. Can you please check the newest version of the agent if it does work for you?

**Comment by rfgamaral** [comment]
Two questions:

1. Which Plex server version do I need to have installed for this? I'm on 0.9.12.19 and it seems this is the latest one available.
2. Will I have to remove my libraries and re-add them?

**Comment by SlrG** [comment]
Ah. Then you will have to wait a bit longer. It's implemented in a later version. I tested on 0.9.14.4. As for the second question, I believe refreshing is sufficient, no need to re-add everything.

**Comment by rfgamaral** [comment]
Is that a alpha/beta available only for Plex Pass members or is it already available to the public and I just can't see it for some reason?

How exactly did you fix this on the importer? I took a quick look to the commit but couldn't understand exactly what it was doing (Python is not my strong suite). I might be mistaken but I believe your fix is slightly different than what I suggested here. But I'm assuming the end result is the same.

**Comment by SlrG** [comment]
It's only available for Plex Pass members for now. But I'm sure it will be released to the public sooner or later. The "fix" are these lines:
```
# Sort Title
try:
    metadata.title_sort = nfoXML.xpath('sorttitle')[0].text.strip()
except:
    self.DLog("No <sorttitle> tag in " + nfoFile + ".")
    pass
```
Basically thats exactly what you proposed. It takes the sort title from the nfo and puts it into plex title_sort attribute. The problem was until now, that plex had not title_sort attribute first. And even after this was added it was not popagated to the web interface. With one of the newest plex pass versions this is fixed too.

**Comment by rfgamaral** [comment]
Cool :)

I'll be sure to test that out as soon as I get access to that new version. I'll try to not forget about this issue and report back. Closing it in the process if it's fixed.

Thanks for all your work.

**Comment by SlrG** [comment]
Does it work as intended? Please close, if you are satisfied.

**Comment by rfgamaral** [comment]
I don't use Plex anymore thus I don't use this. Sorry no taking care of this issue sooner.

Thanks for looking into it :)
