### ISSUE TITLE
Add TheMovieDB support

### ISSUE THREAD

**Issue by mbirth** [gboudreau/XBMCnfoMoviesImporter.bundle#65]
Please add support to use TheMovieDB as an alternative and allow contributing to it, too.

```
        accepts_from = ['com.plexapp.agents.localmedia','com.plexapp.agents.opensubtitles','com.plexapp.agents.podnapisi','com.plexapp.agents.subzero','com.plexapp.agents.themoviedb']
        contributes_to = ['com.plexapp.agents.themoviedb']
```

This way, we can use NFO files if available and fall back to TheMovieDB if they're missing.

**Comment by DreamStatic** [comment]
Is this idea possible? Be nice to still get trailers and extras by continuing on to TheMovieDB and Freebase.

**Comment by SlrG** [comment]
Adding those lines is possible, but it has no effect other than that you can choose other agents in conjunction. But thats it. No other data gets pulled and I was not able to find out why. So at the moment this sadly doesn't work. Sorry. :( If anybody has an idea what is going wrong, I would welcome any help.

**Comment by mbirth** [comment]
From what I gathered, you have to query the other plugins yourself. I didn't dig too deep into it yet, but in one of the default plugins, I found several lines of code which seem to forward the data to another plugin and analyse the result.

**Comment by SlrG** [comment]
Could you give me a pointer where exactly you found those lines? Maybe they will help to enlighten me. :)

**Comment by mbirth** [comment]
Take a look at `Resources/Plug-ins/TheMovieDB.bundle/Contents/Code/__init__.py`, esp. the method `PerformTMDbMovieSearch()` and the class `TMDbAgent(Agent.TV_Shows)`.

**Comment by SlrG** [comment]
Thank you. :) I'll take a look.
