### ISSUE TITLE
Import <tag> fields into Plex Collection?

### ISSUE THREAD

**Issue by ConvertApple** [gboudreau/XBMCnfoMoviesImporter.bundle#66]
Would it be possible to add the tag fields now available in Kodi to Plex Collections (or an option to do so). 

Here is an example nfo file for a music video with 3 tag fields (I use them to mark files as favorites for different people) :- 

`<?xml version="1.0" encoding="utf-8" standalone="yes"?>
<musicvideo>
    <title>Get Lucky</title>
    <originaltitle>Get Lucky</originaltitle>
    <rating>7</rating>
    <epbookmark>0.000000</epbookmark>
    <year></year>
    <top250>0</top250>
    <track>-1</track>
    <album>MusicVideo</album>
    <votes></votes>
    <outline></outline>
    <plot></plot>
    <tagline></tagline>
    <runtime>7</runtime>
    <thumb></thumb>
    <mpaa>Rated NR</mpaa>~~~~
    <playcount>0</playcount>
    <lastplayed></lastplayed>
    <id></id>
    <genre>Electronic</genre>
    <country></country>
    <set></set>
    <premiered></premiered>
    <status></status>
    <code></code>
    <aired></aired>
    <trailer></trailer>
    <fileinfo>
        <streamdetails>
            <video>
                <codec>avc1</codec>
                <aspect>1.77777779</aspect>
                <width>1280</width>
                <height>720</height>
                <durationinseconds>470</durationinseconds>
                <stereomode></stereomode>
            </video>
            <audio>
                <codec>aac</codec>
                <language>Und</language>
                <channels>2</channels>
                <default></default>
            </audio>
        </streamdetails>
    </fileinfo>
    <artist>Daft Punk</artist>
    <resume>
        <position>0.000000</position>
        <total>0.000000</total>
    </resume>
    <dateadded>2016-04-07 08:51:16</dateadded>
    <tag>JS</tag>
    <tag>HS</tag>
    <tag>AS</tag>
</musicvideo>`

**Comment by ConvertApple** [comment]
Update: I cloned your XBMCnfoMoviesImporter.bundle and created XBMCnfoMusicVideosImporter.bundle to handle reading Kodi MusicVideo nfo files. With  bit of gediting here and there + a mod to line 532 to:- sets = nfoXML.xpath('tag')
it's all working great. So I can select the original plugin or my musicvideos one depending on what the library is handling.

**Comment by SlrG** [comment]
Its great you got it working. :) Maybe you can consider to release your modified agent for others to use? I imagine there might be interest. And as it is open source, it would be no problem.
