### ISSUE TITLE
Help with installation

### ISSUE THREAD

**Issue by fabiocannizzo** [gboudreau/XBMCnfoMoviesImporter.bundle#67]
Hi. Just tried to download and install the agent. I run plex server on a headless Linux arch system and access it via the web interface.
I use plex 0.9.16.6
In the movie library setting I select XBMCnfoImporter from the drop down list. 
All movies are in standalone directory containing a file named movie.nfo, created with tinyMediaManager (should be xbmc compatible). 
The metadata does not get loaded. 

How can I debug the problem further? I am mot a python programmer, but it seems to me the source code contains lot of logging, where are these log messages suppose to go? Thanks. A lot.

Fabio

**Comment by Sakujakira** [comment]
Hey Fabio,

im not sure about the current Situation, but about 3 years ago the nfo files must be named like <moviename>.nfo and movie.nfo would not be recognized. 

Sakujakira

**Comment by Sakujakira** [comment]
There you will find the current Log directory:
https://support.plex.tv/hc/en-us/articles/200250417-Plex-Media-Server-Log-Files

**Comment by SlrG** [comment]
Please make sure to enable debug logging in the agents settings when creating the library or you will get a lot less logging. movie.nfo should still work, so thats not the problem IMHO.

**Comment by fabiocannizzo** [comment]
Thanks both. I can see it is working fine now. However, it only works for new movies I add to the library, it does nothing for movies which were in the library already, not even if I do refresh-all. Do I have to delete completely the database and rebuild it?

**Comment by SlrG** [comment]
Hmm... Artwork is cached by plex and new artwork often gets added but not shown by plex. It is user changeable but it is a manual process, which is not really feasible for a lot of movies. As the scanning is rather quick, it is better to recreate the whole library. I found no way to force plex to kill the cache yet. If anybody knows a way, I would welcome any tips or help.
