### ISSUE TITLE
Title Sort Order/Set Fail

### ISSUE THREAD

**Issue by fnwc** [gboudreau/XBMCnfoMoviesImporter.bundle#71]
It seems like when I do a library refresh or update of movies, the sort order and the set tag both are ignored on some movies.

However, I can fix this by doing an unmatch and match in the plex web UI. Then the sort order and set tags are properly assigned (set => collection).

Not sure what's causing this, but I did a complete library refresh.

I have a large library (4000+ movies), maybe something is getting hung up?

This movie scanned correctly:

**A Nightmare On Elm Street**
[Sort Title](http://imgur.com/Cco5xrQ)
[Tags](http://imgur.com/wpdWGhA)

This movie didn't scan correctly, but was 'fixed' when I unmatched and then matched it:

**Freddy's Dead: The Final Nightmare**
[Sort Title](http://imgur.com/OTa34Ae)
[Tags](http://imgur.com/euuLZuw)
[Sort Title (Unmatched/Matched)](http://imgur.com/7pvDdxY)
[Tags (Unmatched/Matched)](http://imgur.com/4fQ4571)

It's inconsistent and seems random, almost like the scanner simply fails on some movies or something.

**Comment by SlrG** [comment]
Can you please enable debug logging in the agents settings and get me all generated log files of the XBMCnfoMovies agent when creating the library? Maybe I can see something in the logs. As you describe it as inconsistent however, I have not much hope that I'll see something in there. But lets give it a try anyways.

**Comment by fnwc** [comment]
Hmmm, so I created an entirely new library, called "MoviesTest" and readded all of my movies. Everything imported fine, as far as I can tell.

My only guess is that Plex has some kind of caching it does that prevents re-reading of movies, as my original "Movies" library was scanned using the default Plex scanner, and then later changed over to the XBMCnfoMoviesImporter scanner.

Even doing a refresh didn't work, but creating an entirely new library did.

**Comment by SlrG** [comment]
Thanks for reporting. Plex caching is indeed a problem. I wish agents had the possibility to purge all old data if they choose to do so.

**Comment by MarkCanada** [comment]
I think to remember that it helped me to delete the contents of ...\Plex Media Server\Plug-in Support\Caches\com.plexapp.agents.xbmcnfo when I ran into the issue a few months ago.
Shut down Plex, make a backup of that folder somewhere and delete it then restart Plex.
...at least that's how I remember it...

**Comment by fnwc** [comment]
Might be nice to put this somewhere in the documentation, so people are aware that this might be an issue. Most people will already have a scanned library by the time they get this plugin, I'm guessing.
