### ISSUE TITLE
Fanart and poster not visible

### ISSUE THREAD

**Issue by cr4nk89** [gboudreau/XBMCnfoMoviesImporter.bundle#72]
Hi,
Im using Plex Version 1.1.3.2700 on DS1815+ and the newest XBMCnfoMoviesImporter and TVImporter but it doesnt show my art. I think it found them because in the content/art folder are fanart and poster pictures.
But I cant find them in webinterface or in apps.

**Comment by cr4nk89** [comment]
Okay I recently found out that  in version 0.9.16.3 the pictures are showing up on my screen. So it must be a Plex problem?!

**Comment by SlrG** [comment]
Please enable debug logging in the agents settings and create a new library adding some of your movies. Zip up all logs of the agent and upload to some cloud service. Drop me a link so I can take a look at it.
