### ISSUE TITLE
Scanner no longer pulling in collection info

### ISSUE THREAD

**Issue by jwaltrip4** [gboudreau/XBMCnfoMoviesImporter.bundle#73]
Latest Plex and XMBCNFO as of this date.

using TMM to create NFO files

when I scan in movie, the collection info is not there.

**Comment by SlrG** [comment]
Do you have debug logging enabled? Any errors in the logs? Probably its another thing broken by the latest changes within plex.

**Comment by jwaltrip4** [comment]
debugging not on.  Do you need me to collect logs?  What do you need me to do?
- debug on
- refresh library?

**Comment by SlrG** [comment]
Yes exactly. Then zip up the agents logs and upload to some sharing service and send me a link. I'll have a look at them.

**Comment by SlrG** [comment]
Can you download the newest version of the agent and check if this fixes your problem? I think I found the error that occurs when using with the newest plex versions.

**Comment by jwaltrip4** [comment]
Still not working.

I have captured the logs.
Plex debugging on, and XMBCNFO debug on

Logs:
https://forums.plex.tv/discussion/250855/posting-logs-for-xmbc-nfo-movie/p1?new=1

**Comment by jwaltrip4** [comment]
this is with latest agent.
Plex is 1.3.3.3148

**Comment by jwaltrip4** [comment]
Any thoughts on issue?

**Comment by SlrG** [comment]
Please install (this)[https://github.com/SlrG/XBMCnfoMoviesImporter.bundle/archive/setproblem.zip] testing version. And capture the log files again. Sadly there were no informations on what fails for you in the last logs you provided. In the testing version I changed the logging in the hope to get more useful info.

**Comment by jwaltrip4** [comment]
Here it is

https://1drv.ms/f/s!AuqpwOQiy5rxjTaCWMuto2pHjMHJ

**Comment by SlrG** [comment]
Hmm... All your collection info appears to be empty, but no errors are in the logs. Can you zip up the folders of two or three of your movies which you know have collection info and upload them for me to check? Please leave out the movie files itself, I need only the folders with nfo files and art.

**Comment by jwaltrip4** [comment]
Zip was sent. in email.
https://1drv.ms/f/s!AuqpwOQiy5rxjTaL7P7RnsHbJ2eT

**Comment by SlrG** [comment]
Thank you for providing your metadata. I found the reason for your problem. At the moment the agent expects a

`<set>Title of Collection</set>`

tag to pull the collection info. In your files you have
 ```
<set>
       <name>The Fast and the Furious Collection</name>
        <overview>An action film series centered on illegal street racing and heists.</overview>
 </set>
```
Maybe TinyMediaManager has an option to make its nfo files Kodi compatible? Its nice to invent new features like a description of the set contents, but if it is not compatible to the media centers, it is for nought and breaks things. I can't find anything about supporting this in the Kodi wiki and as this is basically an XBMC/Kodi agent I don't really want to make it TinyMediaManager compatible.

Rant (not directed on you): I hate it with a passion, that there is no clear standard for nfo files everyone follows. That would make it easier for everyone to always support the correct tags.

**Comment by MuetzeOfficial** [comment]
I had the same problem. I change following lines and it's work for me....
`                    setname = nfo_xml.xpath("set")[0].xpath("name")[0].text
                    log.debug('Enhanced set tag found: ' + setname)
                except:
                    log.debug('No enhanced set tag found...')
                    pass
                try:
                    # fallback to flat style set tag
                    if not setname:
                        setname = nfo_xml.xpath("set")[0].text`

replace with:
`                    setname = nfo_xml.xpath('set')[0].xpath('name')[0].text
                    log.debug('Enhanced set tag found: ' + setname)
                except:
                    log.debug('No enhanced set tag found...')
                    pass
                try:
                    # fallback to flat style set tag
                    if not setname:
                        setname = nfo_xml.xpath('set')[0].text`

**Comment by SlrG** [comment]
@jwaltrip4 
I forgot to inform you, that I included code to fix to this problem. Sadly it was still buggy as @MuetzeOfficial found out. I replaced the quotes as he suggests and hope it is working for you now. Please give it a try and close the issue, if fixed.
