### ISSUE TITLE
I seem to seee 2 versions of this. ?

### ISSUE THREAD

**Issue by jwaltrip4** [gboudreau/XBMCnfoMoviesImporter.bundle#84]
One by you. and one by SirG....

Sorry, don't really know how GitHub work with this....

Are these 2 separate versions?

**Comment by Sakujakira** [comment]
With Git you are able to fork, or clone, someones project. So @SlrG  made a fork of this one, also i did, everyone could.  Currently all Fixes by @SlrG are merged into this project, so you should continue to use this project.

**Comment by SlrG** [comment]
This is the official version and recommended version. My repository is a fork I am using to test things out, before I push them to the official version. It is not recommended to use a version from my repo, as it might very well be broken. I know things in the official repo are sometimes broken too, but that is mostly, when a bug escaped me on my personal repo.

**Comment by jwaltrip4** [comment]
Much appreciate the responses.  thanks
