### ISSUE TITLE
[SUGGEST] Select extension of local info file

### ISSUE THREAD

**Issue by icore77** [gboudreau/XBMCnfoMoviesImporter.bundle#87]
Hi, 
I'm using XML extension instead of NFO.
I prefer this because NFO extension is assigned to another type of data (in my case) and I would like to suggest you to have the option into the agent to select which type of extension the agent is able to scan for local info.
Default is NFO but let someone to specify XML (or other type) as needed (option into agent will be nice).

Thanks for your work, I really appreciate this agent.

**Comment by SlrG** [comment]
While I understand your request, this is called XBMCnfoMoviesImporter and XBMCnfoTVImporter. Its no generic xml importer but is intended to import the information from an exported XBMC/Kodi database into plex. Basically all Media Managers I know use the nfo extension and I am not going to deviate from that standard.

**Comment by icore77** [comment]
Yes, I understand your opinion too.
That's why this is a suggestion.

Thanks for your reply.
Closed point.
