### ISSUE TITLE
No longer appears in unsupported appstore

### ISSUE THREAD

**Issue by gbcox** [gboudreau/XBMCnfoMoviesImporter.bundle#88]
I just noticed that this no longer shows up in metadata agents for the unsupported appstore.  Is this user error on my part or did something else happen?

**Comment by gbcox** [comment]
Never mind, for some reason had to manually migrate, re-import.  Not sure why, but all working now fine.

**Comment by SlrG** [comment]
Just gave it a try, too. :) It works fine for me, so it really was a hiccup on your system. I'm glad you got it resolved.
