### ISSUE TITLE
Get fanart and poster in other folder

### ISSUE THREAD

**Issue by SOz92** [gboudreau/XBMCnfoMoviesImporter.bundle#89]
Hi, i have a question, it's possible to get the poster for the movies in other path? Example:
V:\Movies\movie1.mkv
V:\Movies\movie2.mkv
V:\Movies\Posters\movie1-poster.jpg
V:\Movies\Posters\movie2-poster.jpg

I don't know how to do that, someone here can help me?

**Comment by SlrG** [comment]
This is not an issue. It's no error or bug in the agents. It's just a feature request where you want it do something it was not designed to. So please understand, that I'll be closing it.

I'll give you some tips however on how you can achieve your goal:
You need to fork the agents, then add an option to the agents preferences file DefaultPrefs.json, named "posterfolder" or how you like it. By default it would be empty but a path can be entered in plex agents settings dialog. This should point to your poster folder.

Then you go in the source of the respective agent (__init__.py - which is a python file) and search for the section where the poster is added. For the movies agent it is currently line 257. There you add a section where you change the path to use the one given in the agents settings plus moviename-poster.jpg and it should work.

You'll need some github and git skills as well as python programming skills, but all that is easily attainable by reading some online sources and looking and understanding how the agents already work.
