### ISSUE TITLE
Assistance on actors photos

### ISSUE THREAD

**Issue by gbcox** [gboudreau/XBMCnfoMoviesImporter.bundle#93]
Hello, I saw where you are adding support for actors photos and am trying to figure out how to use it.  After looking at the code I did the following, but obviously have got it wrong because it isn't working.
In the directory where I have the poster.jpg, background.jpg, video.mp4 and movie.nfo files I added a .actor directory.
I had:
`<actor>John Doe</actor>
`
so in the .actor directory I created the thumb file and gave it the name of `John_Doe.jpg`

I also selected 'global' in settings for actor thumb location.  I left location as:  http://localhost
which is working for the existing movie library... 

what am I missing?  Thanks - and appreciate you adding the ability to include actor thumbs.

**Comment by gbcox** [comment]
I found this discussion and am reviewing... 
[https://forums.plex.tv/discussion/38402/metadata-agents-for-exported-xbmc-library/p72](url)

**Comment by gbcox** [comment]
Thanks, I figured it out.  It was the the fact I needed to setup the thumbs via http...

**Comment by SlrG** [comment]
Cool you figured it out yourself. :) Not all users do research that much themself. As you found out, plex only supports actor thumbs from http sources and not local files. It makes it really complicated IMHO, but only the plex devs could change it.
