### ISSUE TITLE
Extract Actors photos from Plex?

### ISSUE THREAD

**Issue by gbcox** [gboudreau/XBMCnfoMoviesImporter.bundle#94]
I had to rebuild my system and of course I had backups of everything EXCEPT the directory where I had all the actor photos.  I know that plex keeps these somewhere.  Do you know how to extract them back out so I could keep them as a separate backup in case something happens to my plex library or would it just be easier to over time rebuild them as I need them.  As an aside, I sometimes notice a better photo, but have found that once you load a particular actor photo, that's it.  I haven't figured out how to replace photos.  Seems that once they are in Plex, they aren't replaced.

**Comment by SlrG** [comment]
That's sad to hear. :( I had something like this happen, to me too and I can feel your pain. Sadly I don't think plex stores the actor thumbs. AFAIK in the Media directory, there are only posters, art and such. I think the thumbs are stored as hyperlinks in the plex db. If you replaced a photo and want it to change in plex it is possible you will have to recreate the whole library. Only the first per actor is stored I believe.

**Comment by gbcox** [comment]
Thanks for the quick reply.  It will be a bit of a PITA but I have a path forward to rebuild... yeah, all the previous actors still show up perfectly fine even though the source disk no longer exists - so the images are in there somewhere, but probably not worth the effort to try to figure it out.  I'll just redo them as needed and MAKE SURE I BACK IT UP this time!  LOL...

**Comment by SlrG** [comment]
Hmm... Could you try clearing the browser cache or using another browser, which has no cached data to access your plex? Also temporarily disable your networking. If the actors are showing even then, they are indeed cached somewhere by plex. It could be interesting to find out where.

**Comment by gbcox** [comment]
You are 100% correct.  It never occurred to me that the images were being grabbed from cached data - duh!  Thanks again for taking the time to respond.

**Comment by SlrG** [comment]
No problem. :) But just to be clear, they are gone if you do as I requested? So they are not stored by plex but in the browsers cache?

**Comment by ThomFabian** [comment]
Sorry for resurrecting this thread from the dead, but I wanted to chime in concerning your previous question about clearing browser cache to see new actor photos.  It appears that did not work for me.  I followed this process:
1) Set up test plex library with 3 actor photos to test dimensioning (photos served by local Qnap web server).
2) After some configuring, I was able to get them to show.
3) Edited photos and reuploaded them to Qnap server.
4) Old photos still appeared after metadata refresh
5) cleared browser cache - old photos still showed
6) tried different  browser - old photos still showed
7) navigated directly to photo (using url) - new photo showed in browser (thus Qnap is serving new photo)
8) tried plex on different system - old photos still showed
9) added new photos for new actors - new photos showed for new actors, but old photos still showed for previously added actors
10) deleted library and set it up again - no change - old photos still showed

This leads me to guess that perhaps these photos are being cached internal to Plex?  Its not a big deal, just wanted to give you more information.  Thanks for the plugin!
