### ISSUE TITLE
Import actor images from SMB file share

### ISSUE THREAD

**Issue by pdavidd** [gboudreau/XBMCnfoMoviesImporter.bundle#95]
Hello,

My XBMC/KODI setup is configured with a central actors folder accessible from a SMB share on my network.  Would it be possible to configure this importer to be able to get the images from that share.  The image locations are stored in the .NFO files with each actor in the format: smb://username:password@serverIP/share/../../image.jpg

**Comment by SlrG** [comment]
Hi,

while I admit this would be nice, it sadly does not work. Plex only supports http links for actor thumbs. There is nothing the agent can do to change that. You will have to setup a http server which points to the same directory as your samba share.
