### ISSUE TITLE
Subtitle Support?

### ISSUE THREAD

**Issue by pdavidd** [gboudreau/XBMCnfoMoviesImporter.bundle#96]
Hello,

Is it possible to add subtitle support?  

I know I can turn on local media assets to get the subtitles, however this also gets additional artwork, which is enlarging my metadata folder by an additional 50%.  Also, I need to use this nfoinporter for the posters, since plex does not support the [moviename]-poster.jpg format that all my posters are in.

**Comment by SlrG** [comment]
No sorry that is not possible. I don't have the knowledge and time to do that. But if you can do it, a pull request would be welcome.

You can try to disable the agents artwork support in settings which should prevent the additional 50% size increase. But it will probably prevent your -poster.jpg from being recognized, too. Maybe you could rename them.

**Comment by glitch452** [comment]
Hi Again, I'm interested in taking this on.  Can you point me in the direction of any good documentation to help get me up to speed with how to create an agent for Plex?

**Comment by SlrG** [comment]
Firstly you should check if maybe there is a subtitle agent you could already use in combination with the XBMCnfoImporter Agents to do what you want. It would make no sense, to reinvent the wheel.

If you decide there is none and you want to start a new one or extend an existing one, you have to start learning about python. That is the programming language used to develop plex agents. If you have no knowledge there, you could start with some online python courses.

There was a plex developer portal containing info for developers once. Sadly this is abandoned by plex and gone from the web. Today it is very hard to find info. The best way is to check the source code of [plex stock agents](https://github.com/plexinc-agents) and of agents developed by others and start from there. Also if you search the web, there are bits and pieces here and there.
https://forums.plex.tv/discussion/266450/how-can-i-get-started-writing-a-plugin-for-plex
[PlexPluginFramework.pdf](https://github.com/gboudreau/XBMCnfoMoviesImporter.bundle/files/1289822/PlexPluginFramework.pdf)

As you want the functionality from the local media assets agent, you can look at that and see, how it is handled there. Of course taking that 1:1 will probably not work and could create copyright problems.

Lastly you should look through and get to understand the [XBMCnfoMoviesImporter](https://github.com/gboudreau/XBMCnfoMoviesImporter.bundle) and [XBMCnfoTVImporter](https://github.com/gboudreau/XBMCnfoTVImporter.bundle) source.

**Comment by glitch452** [comment]
Hey, Thanks for the info!  I had gotten started and was going along the same lines as you recommended.  I read the starter manual for Python.  Its similar enough to other languages that I am able to work with it (googling things when I get stuck).  There may be subtitle importers out there, but I am hoping to use this importer exclusively for movies, so my ultimate goal will be to get the subtitle module up and running for this importer.  It may be a bit more work, but this will be a bit of a hobby project for me to learn some Python.  

I WAS hoping that you were aware of some Plex developer api documentation that I somehow wasn't able to find on google, but I guess that doesn't exist any more so... yeah I've been reading through the code for this importer to try and get a handle on the basics.  After some more digging I was able to find a document that outlines some of the Plex API; which is probably a remnant form the developer portal.  I started reading through the builtin subtitle importer (thanks for that link)... and I should be able to use that to get an idea of how to import the subtitles with this importer (without directly copying it).  

I've gotten off to a good start, I am able to search for and locate files with the proper extensions.  Now I have to get the language mapping working and then the import the subtitles.  I'll let you know when I have something more concrete.  I'm also new to Git Hub, so I'll send a pull request and play with that once I get something working.  

Is there a way to send private messages on here, or could I get your email address?  Maybe you can give me some tips on Git Hub contributions.  I'm interested in the etiquette for contributing here, etc... Im not sure how the process works.  Ie. Would I just submit a contribution then it gets approved by someone?    

Thanks!
